plugins:
  siwe_enabled:
    client: true
    default: false
  siwe_statement: ''
  siwe_prefix:
    client: true
    default: ''
  siwe_network:
    client: true
    default: 'mainnet'
  siwe_infura_id:
    client: true
    default: ''
  siwe_torus:
    client: true
    default: false
  siwe_portis_id:
    client: true
    default: ''
  siwe_fortmatic_key:
    client: true
    default: ''
  siwe_coinbase:
    client: true
    default: false
  siwe_expiration_time:
    client: false
    default: 604800 #one week
  siwe_not_before:
    client: false
    default: 0 #milisseconds
  siwe_request_id:
    client: true
    default: true